"""Write tile GLBs (pygltflib), compress with gltf-transform meshopt, and emit track.json."""
import json
import os
import shutil
import struct
import subprocess

import numpy as np
import pygltflib as g

from sr.schema import validate_track
from sr.tiles import tile_name

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
GAME_DIR = os.path.join(ROOT, "game")

# Greybox palette. 0.2 replaces these with textured materials of the same names.
MATERIALS = {
    "road": (0.16, 0.16, 0.17, 1.0),
    "terrain": (0.54, 0.52, 0.38, 1.0),
    "terrain_grass": (0.37, 0.48, 0.25, 1.0),
    "terrain_scrub": (0.55, 0.51, 0.33, 1.0),
    "terrain_wood": (0.22, 0.31, 0.21, 1.0),
    "terrain_sand": (0.76, 0.7, 0.56, 1.0),
    "terrain_rock": (0.5, 0.47, 0.44, 1.0),
    "terrain_saltpond": (0.72, 0.45, 0.44, 1.0),
    "terrain_paved": (0.42, 0.42, 0.43, 1.0),
    "water": (0.13, 0.31, 0.48, 1.0),
    "building": (0.62, 0.62, 0.60, 1.0),
    "barrier": (0.95, 0.42, 0.05, 1.0),
    "bridge": (0.45, 0.45, 0.47, 1.0),
    "billboard_frame": (0.30, 0.31, 0.33, 1.0),
    "billboard_lamp": (0.93, 0.90, 0.80, 1.0),
}
# One material per billboard content slot. They are identical here and told apart by the runtime,
# which hangs a different face texture on each; the slot has to exist in the geometry because an
# instanced node carries exactly one material.
for _slot in "abcdefghijklmn":
    MATERIALS[f"billboard_face_{_slot}"] = (0.86, 0.86, 0.84, 1.0)
MATERIALS["line_white"] = (0.92, 0.92, 0.90, 1.0)
MATERIALS["line_yellow"] = (0.90, 0.72, 0.12, 1.0)
MATERIALS["bridge_steel"] = (0.75, 0.21, 0.14, 1.0)   # International Orange
MATERIALS["bridge_metal"] = (0.60, 0.62, 0.64, 1.0)   # painted grey Bay Bridge steel
MATERIALS["foliage"] = (0.18, 0.31, 0.16, 1.0)
MATERIALS["foliage_dark"] = (0.10, 0.22, 0.14, 1.0)
MATERIALS["foliage_palm"] = (0.20, 0.42, 0.24, 1.0)
MATERIALS["foliage_orchard"] = (0.34, 0.48, 0.20, 1.0)
MATERIALS["foliage_scrub"] = (0.39, 0.37, 0.22, 1.0)
MATERIALS["trunk"] = (0.27, 0.21, 0.16, 1.0)
MATERIALS["guardrail"] = (0.60, 0.62, 0.64, 1.0)
MATERIALS["sidewalk"] = (0.66, 0.65, 0.62, 1.0)
MATERIALS["flower_pink"] = (0.95, 0.28, 0.58, 1.0)
MATERIALS["flower_white"] = (0.95, 0.93, 0.84, 1.0)
MATERIALS["flower_blue"] = (0.36, 0.60, 0.94, 1.0)
MATERIALS["flower_purple"] = (0.62, 0.34, 0.82, 1.0)
MATERIALS["slime_scenery"] = (0.32, 0.78, 0.20, 1.0)
# Facades. `building` stays the fallback and keeps the runtime's procedural window grid; these five
# are what a footprint's OSM tag maps to (`sr/buildings.py:FACADE`), each with its own texture.
MATERIALS["building_glass"] = (0.20, 0.31, 0.34, 1.0)
MATERIALS["building_stucco"] = (0.70, 0.64, 0.55, 1.0)
MATERIALS["building_concrete"] = (0.60, 0.59, 0.57, 1.0)
MATERIALS["building_metal"] = (0.62, 0.64, 0.65, 1.0)
MATERIALS["building_parking"] = (0.52, 0.51, 0.49, 1.0)
# Landmark materials keep a recognisable building's observed palette out of the generic five-way
# facade lottery. They are still shared across every route and generated by sr/textures.py.
MATERIALS["building_landmark_glass"] = (0.12, 0.25, 0.29, 1.0)
MATERIALS["building_landmark_pale"] = (0.78, 0.76, 0.69, 1.0)
MATERIALS["building_landmark_solar"] = (0.10, 0.17, 0.19, 1.0)
MATERIALS["building_landmark_metal"] = (0.72, 0.73, 0.70, 1.0)
MATERIALS["house_roof_slate"] = (.26, .29, .33, 1.)
MATERIALS["house_roof_tile"] = (.59, .35, .26, 1.)
MATERIALS["house_trim"] = (.84, .81, .73, 1.)
MATERIALS["building_landmark_roof"] = (0.78, 0.78, 0.75, 1.0)

# The contract's table, and the only one that reaches the runtime: a node whose prefix is missing
# here is exported with collider "none", and the runtime honours that over its own defaults. A new
# kind of geometry that is meant to be solid has to be added here or it silently renders and
# nothing ever touches it. docs/CONTRACT.md section 3 is the source of truth.
NODE_COLLIDER = {"road": "trimesh", "terrain": "trimesh", "water": "none", "buildings": "boxes",
                 "bridge": "trimesh", "guardrail": "trimesh", "props_barrier": "instances-box",
                 "props_billboard": "none", "props_slime": "none", "markings": "none", "bridgeworks": "none", "sidewalk": "none", "backdrop": "none",
                 "trees": "none", "flowers": "none", "scenery": "none", "deck": "trimesh"}


def collider_for(node):
    """The collider kind a node name implies, matching docs/CONTRACT.md.

    A `props_` node is looked up whole and then by its longest registered prefix, because one prop
    can need several nodes: the fourteen billboard faces are separate nodes only because instanced
    geometry carries one material per node, and they all mean the same thing to physics."""
    if not node.startswith("props_"):
        return NODE_COLLIDER.get(node.split("_")[0], "none")
    if node in NODE_COLLIDER:
        return NODE_COLLIDER[node]
    hit = [k for k in NODE_COLLIDER if k.startswith("props_") and node.startswith(k + "_")]
    return NODE_COLLIDER[max(hit, key=len)] if hit else "instances-box"


class _Buffer:
    def __init__(self):
        self.blob = bytearray()
        self.views = []
        self.accessors = []

    def _pad(self):
        while len(self.blob) % 4:
            self.blob.append(0)

    def add(self, arr, component_type, accessor_type, target=None, minmax=False):
        self._pad()
        raw = np.ascontiguousarray(arr).tobytes()
        view = g.BufferView(buffer=0, byteOffset=len(self.blob), byteLength=len(raw), target=target)
        self.blob.extend(raw)
        self.views.append(view)
        acc = g.Accessor(bufferView=len(self.views) - 1, componentType=component_type, count=len(arr), type=accessor_type)
        if minmax:
            acc.min = np.asarray(arr).min(axis=0).tolist(); acc.max = np.asarray(arr).max(axis=0).tolist()
        self.accessors.append(acc)
        return len(self.accessors) - 1


def _yaw_quat(yaw):
    return [0.0, float(np.sin(yaw / 2)), 0.0, float(np.cos(yaw / 2))]


def write_tile_glb(path, node_meshes, instances, boxes, extras_by_node=None):
    """node_meshes: {node: Mesh}; instances: {node: {positions, yaws, mesh, halfExtents}}; boxes: collider list."""
    gltf = g.GLTF2(asset=g.Asset(version="2.0", generator="silicon-rush pipeline"))
    buf = _Buffer()
    mat_index = {}
    for name, rgba in MATERIALS.items():
        gltf.materials.append(g.Material(name=name, pbrMetallicRoughness=g.PbrMetallicRoughness(baseColorFactor=list(rgba), metallicFactor=0.0, roughnessFactor=0.9)))
        mat_index[name] = len(gltf.materials) - 1
    nodes = []

    def add_mesh(mesh, name):
        pos = buf.add(mesh.positions, g.FLOAT, g.VEC3, g.ARRAY_BUFFER, minmax=True)
        nor = buf.add(mesh.normals, g.FLOAT, g.VEC3, g.ARRAY_BUFFER)
        uv = buf.add(mesh.uvs, g.FLOAT, g.VEC2, g.ARRAY_BUFFER)
        idx = buf.add(mesh.indices.astype(np.uint32), g.UNSIGNED_INT, g.SCALAR, g.ELEMENT_ARRAY_BUFFER)
        attributes = g.Attributes(POSITION=pos, NORMAL=nor, TEXCOORD_0=uv)
        if mesh.facade is not None:
            attributes.TEXCOORD_1 = buf.add(mesh.facade, g.FLOAT, g.VEC2, g.ARRAY_BUFFER)
        prim = g.Primitive(attributes=attributes, indices=idx, material=mat_index[mesh.material])
        gltf.meshes.append(g.Mesh(name=name, primitives=[prim]))
        return len(gltf.meshes) - 1

    
    boxes_written = False
    for node, mesh in sorted(node_meshes.items()):
        if mesh.is_empty():
            continue
        extras = {"collider": collider_for(node)}
        if not boxes_written and collider_for(node) == "boxes":
            extras["boxes"] = boxes
            boxes_written = True
        if extras_by_node and node in extras_by_node:
            extras.update(extras_by_node[node])
        gltf.nodes.append(g.Node(name=node, mesh=add_mesh(mesh, node), extras=extras))
        nodes.append(len(gltf.nodes) - 1)

    used_instancing = False
    for node, inst in instances.items():
        if not inst.get("positions"):
            continue
        used_instancing = True
        m = add_mesh(inst["mesh"], node)
        pos = np.asarray(inst["positions"], dtype=np.float32)
        rot = np.asarray([_yaw_quat(y) for y in inst["yaws"]], dtype=np.float32)
        t = buf.add(pos, g.FLOAT, g.VEC3)
        r = buf.add(rot, g.FLOAT, g.VEC4)
        attrs = {"TRANSLATION": t, "ROTATION": r}
        scales = np.asarray(inst.get("scales") or [[1.0, 1.0, 1.0]] * len(pos), dtype=np.float32)
        if not np.allclose(scales, 1.0):                     # only pay for SCALE where it is used
            attrs["SCALE"] = buf.add(scales, g.FLOAT, g.VEC3)
        extras = {"collider": collider_for(node), "halfExtents": inst["halfExtents"]}
        if extras_by_node and node in extras_by_node:
            extras.update(extras_by_node[node])
        gltf.nodes.append(g.Node(name=node, mesh=m, extras=extras,
                                 extensions={"EXT_mesh_gpu_instancing": {"attributes": attrs}}))
        nodes.append(len(gltf.nodes) - 1)
    if used_instancing:
        gltf.extensionsUsed = ["EXT_mesh_gpu_instancing"]
    gltf.bufferViews = buf.views
    gltf.accessors = buf.accessors
    gltf.buffers = [g.Buffer(byteLength=len(buf.blob))]
    gltf.scenes = [g.Scene(nodes=nodes)]
    gltf.scene = 0
    gltf.set_binary_blob(bytes(buf.blob))
    gltf.save(path)
    return path


def compress_meshopt(src, dst):
    """Run gltf-transform meshopt from the game's node_modules. Falls back to a copy if unavailable."""
    npx = shutil.which("npx")
    if not npx:
        shutil.copyfile(src, dst); return False
    r = subprocess.run([npx, "--prefix", GAME_DIR, "--no-install", "gltf-transform", "meshopt", src, dst],
                       capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError("gltf-transform meshopt failed:\n" + r.stdout + r.stderr)
    return True


def write_backdrop(path, node_meshes, compress=True):
    """The resident distant-scenery mesh, written with the same tile writer and no colliders."""
    raw = path + ".raw.glb"
    write_tile_glb(raw, node_meshes, {}, [], None)
    if compress:
        compress_meshopt(raw, path); os.remove(raw)
    else:
        os.replace(raw, path)
    return path


TILE_PACK = "tiles.bin"


def export_track(track, tileset, out_dir, compress=True):
    """Write `tiles/<name>.glb` and `track.json` into out_dir. track is the dict minus tiles.

    **Loose files, one per tile.** itch.io counts files and a thousand is a hard limit with no
    appeal, so what ships is one `tiles.bin` per track -- but that is a *release* shape, and packing
    it here was the wrong place for it. Packing during generation made every rebuild rewrite one blob and one
    index for the whole track, so a one-line change cost a full rebuild, and a checkout that had the
    new index but not the new blob had no older file to fall back on -- which is how a car ended up
    flying through an empty sky.

    The packing now happens in `npm run build`, into `dist/` only (see `game/vite.config.ts`). This
    directory stays loose from beginning to end, and one tile changing is one file rewritten.

    A stale `tiles.bin` from before that change is removed here: leaving it means the runtime keeps
    reading a pack that no longer matches the index beside it."""
    tiles_dir = os.path.join(out_dir, "tiles")
    if os.path.isdir(tiles_dir):
        for old in os.listdir(tiles_dir):
            os.remove(os.path.join(tiles_dir, old))
    os.makedirs(tiles_dir, exist_ok=True)
    stale_pack = os.path.join(out_dir, TILE_PACK)
    if os.path.exists(stale_pack):
        os.remove(stale_pack)
    P = np.asarray(track["spline"]["points"], dtype=np.float64)
    # New exports carry the authoritative 3-D arc beside the points. The private fallback only
    # keeps old unit fixtures readable; build() and synth never emit it.
    S = np.asarray(track["spline"].get("s", track.get("_S")), dtype=np.float64)
    from sr.tiles import s_ranges_for_tile
    tile_entries = []
    for tile in tileset.tiles():
        name = tile_name(*tile)
        raw = os.path.join(tiles_dir, name + ".raw.glb")
        final = os.path.join(tiles_dir, name + ".glb")
        write_tile_glb(raw, tileset.merged(tile), tileset.instances[tile], tileset.boxes[tile],
                       tileset.extras.get(tile))
        if compress:
            compress_meshopt(raw, final); os.remove(raw)
        else:
            os.replace(raw, final)
        ranges = s_ranges_for_tile(P, S, *tile, closed=track["spline"]["closed"])
        tile_entries.append({"name": name, "sRanges": ranges, "bounds": tileset.bounds(tile)})
    doc = {k: v for k, v in track.items() if not k.startswith("_")}
    doc["tiles"] = tile_entries
    validate_track(doc)
    with open(os.path.join(out_dir, "track.json"), "w", encoding="utf-8") as f:
        json.dump(doc, f, ensure_ascii=False, indent=1)
    return doc
